### ISSUE TITLE
Dependency not specified in META6.json

### ISSUE THREAD

**Issue by kjpye** [librasteve/raku-Physics-Measure#70]
Physics::Measure uses Math::Vector, but it's not specified in META6.json.

**Comment by librasteve** [comment]
Ah - turns out that cannot `use Math::Vector` in Measure.rakumod as it stomps on the math operators.

Therefore I have reverted out the dependency on Math::Vector and removed the type constraint of `Real` to continue to allow Math::Vector values dynamically.

Resolved in v2.0.1
